
package cab;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "cabPrinterSOAP", targetNamespace = "http://www.cab.de/WSSchema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CabPrinterSOAP {


    /**
     * Printer Status.
     * Input Values: ESCs, ESCz, ESCi, ESCl, ESCa, ESCj, ESC?, Generic, Label
     * Output Values:
     * Generic: A generic Printer Status,
     * Label: The loaded Label,
     * Other: see Programming manual
     * 
     * 
     * @param parameters
     * @return
     *     returns java.lang.String
     * @throws FaultResponse
     */
    @WebMethod(action = "status")
    @WebResult(name = "statusResponse", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
    public String getPrinterStatus(
        @WebParam(name = "statusRequest", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
        String parameters)
        throws FaultResponse
    ;

    /**
     * List of Formats.
     * Input Value: void
     * Output Value: The Lables stored on the primary card slot
     * 
     * @param parameters
     * @return
     *     returns cab.ListOfFormatsResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "formatlist")
    @WebResult(name = "listOfFormatsResponse", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
    public ListOfFormatsResponse getlistOfFormats(
        @WebParam(name = "listOfFormatsRequest", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
        ListOfFormatsRequest parameters)
        throws FaultResponse
    ;

    /**
     * List of Objects from the loaded Format.
     * Input Value: void
     * Output Value: The Objects from the loaded Format
     * 
     * @param parameters
     * @return
     *     returns cab.ListOfObjectsResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "objectlist")
    @WebResult(name = "listOfObjectsResponse", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
    public ListOfObjectsResponse getlistOfObjects(
        @WebParam(name = "listOfObjectsRequest", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
        ListOfObjectsRequest parameters)
        throws FaultResponse
    ;

    /**
     * List of last printer Jobs.
     * Input Value: void
     * Output Value: The last Printer Jobs
     * 
     * @param parameters
     * @return
     *     returns cab.ListOfJobsResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "joblist")
    @WebResult(name = "listOfJobsResponse", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
    public ListOfJobsResponse getlistOfJobs(
        @WebParam(name = "listOfJobsRequest", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
        ListOfJobsRequest parameters)
        throws FaultResponse
    ;

    /**
     * Load Format.
     * Input Value: The name from the Format
     * Output Value: A processing status
     * 
     * @param parameters
     * @return
     *     returns cab.LoadFormat
     * @throws FaultResponse
     */
    @WebMethod(action = "loadformat")
    @WebResult(name = "loadFormatResponse", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
    public LoadFormat loadFormat(
        @WebParam(name = "loadFormatRequest", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
        String parameters)
        throws FaultResponse
    ;

    /**
     * Print Format.
     * Input Values:
     * The objects (name and value) from the label
     * The JobID from the label
     *  The number of labels
     * Output Value: A processing status
     * 
     * @param parameters
     * @return
     *     returns cab.LoadFormat
     * @throws FaultResponse
     */
    @WebMethod(action = "printformat")
    @WebResult(name = "printFormatResponse", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
    public LoadFormat printFormat(
        @WebParam(name = "printFormatRequest", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
        PrintFormat parameters)
        throws FaultResponse
    ;

    /**
     * Reset the printer.
     * Input Value: void
     * Output Value: A processing status
     * 
     * @param parameters
     * @return
     *     returns cab.AbortAllJobsResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "abortAllJobs")
    @WebResult(name = "abortAllJobsResponse", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
    public AbortAllJobsResponse abortAllJobs(
        @WebParam(name = "abortAllJobsRequest", targetNamespace = "http://www.cab.de/WSSchema", partName = "parameters")
        AbortAllJobsRequest parameters)
        throws FaultResponse
    ;

}
