
package cab;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Web Service for cab label printers
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "cabPrinterWebService", targetNamespace = "http://www.cab.de/WSSchema", wsdlLocation = "http://cgaptestbc.internal.sanger.ac.uk/cgi-bin/soap/services.wsdl")
public class CabPrinterWebService
    extends Service
{

    private final static URL CABPRINTERWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CABPRINTERWEBSERVICE_EXCEPTION;
    private final static QName CABPRINTERWEBSERVICE_QNAME = new QName("http://www.cab.de/WSSchema", "cabPrinterWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://cgaptestbc.internal.sanger.ac.uk/cgi-bin/soap/services.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CABPRINTERWEBSERVICE_WSDL_LOCATION = url;
        CABPRINTERWEBSERVICE_EXCEPTION = e;
    }

    public CabPrinterWebService() {
        super(__getWsdlLocation(), CABPRINTERWEBSERVICE_QNAME);
    }

    public CabPrinterWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CABPRINTERWEBSERVICE_QNAME, features);
    }

    public CabPrinterWebService(URL wsdlLocation) {
        super(wsdlLocation, CABPRINTERWEBSERVICE_QNAME);
    }

    public CabPrinterWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CABPRINTERWEBSERVICE_QNAME, features);
    }

    public CabPrinterWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CabPrinterWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CabPrinterSOAP
     */
    @WebEndpoint(name = "PrinterWebServiceSOAP")
    public CabPrinterSOAP getPrinterWebServiceSOAP() {
        return super.getPort(new QName("http://www.cab.de/WSSchema", "PrinterWebServiceSOAP"), CabPrinterSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CabPrinterSOAP
     */
    @WebEndpoint(name = "PrinterWebServiceSOAP")
    public CabPrinterSOAP getPrinterWebServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cab.de/WSSchema", "PrinterWebServiceSOAP"), CabPrinterSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CABPRINTERWEBSERVICE_EXCEPTION!= null) {
            throw CABPRINTERWEBSERVICE_EXCEPTION;
        }
        return CABPRINTERWEBSERVICE_WSDL_LOCATION;
    }

}
