# version: "3"

# services:
api:
  container_name: api
  restart: always
  build: .
  ports:
    - "8080:8080"
client:
  container_name: client
  restart: always
  build: ./client
  ports:
    - "3000:3000"
  links:
    - api